### ISSUE TITLE
[FEAT] Support yaml configuration for windows OS

### ISSUE THREAD

**Issue by tbhaxor** [automation-co/husky#16]
**Is your feature request related to a problem? Please describe.**

Shell script only works with posix system, but the windows user will not be able to use this application outside cgywin app.

**Describe the solution you'd like**

Instead of having a shell script, have a yaml file with command as array

```yaml

version: 2.0
hooks:
   pre-commit:
       - whoami
```

Now the install command will create the hooks in the `.git/hooks` based on shell, powershell or cmd prompt.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by tbhaxor** [comment]
I can work on this, but it will cause breaking change for next version release

**Comment by tbhaxor** [comment]
If you are interested, please assign this issue to me 😄

**Comment by Aarush-Goyal** [comment]
Hi @tbhaxor 

Thank you for making the issue.

Your solution is quite good but may affect our backward compatibility.

I would be talking with the @automation-co/open-source-team and would get back to you how we can solve this issue.

**Comment by tbhaxor** [comment]
Hey @Aarush-Goyal, my bad. I could have researched before opening the issue

![image](https://user-images.githubusercontent.com/28386721/178074946-0122b985-fd7c-4cd2-a6cb-971e483dcea0.png)

`/bin/sh` works in windows as well. The git installed uses cygwin internally.

**Comment by Aarush-Goyal** [comment]
No problem @tbhaxor 
Thanks for taking out time to contribute to our project 😊.
