### ISSUE TITLE
[FEAT]install should config core.hooksPath, not copy to .git/hooks

### ISSUE THREAD

**Issue by saltbo** [automation-co/husky#24]
Dir `.git/hooks` not managed by git, we should config the hooksPath

https://stackoverflow.com/questions/427207/can-git-hook-scripts-be-managed-along-with-the-repository

**Describe the solution you'd like**
`git config core.hooksPath .husky/hooks`

**Comment by theishanbh** [comment]
Hi @saltbo 

Thank you for making the issue.

I would be talking with the https://github.com/orgs/automation-co/teams/open-source-team and would get back to you how we can solve this issue.

**Comment by theishanbh** [comment]
Hey @saltbo 

We just looked through the issue. 

In fact, `.git/hooks` is managed by Git. It's the default directory from where Git Hooks are run. Husky ( `.husky/hooks` ) is set up as sibling directory to `.git/hooks`. 

When you initialize Husky, the hooks from Husky are getting copied to git hooks folder. 

https://github.com/automation-co/husky/blob/4d2fdbce65b4b27bc37a36c0fccdb3249266bd7e/internal/lib/init.go#L9

Let me know if this answers your query.

**Comment by saltbo** [comment]
![image](https://user-images.githubusercontent.com/17308208/199410789-400b5aa8-dd04-4d0c-ace9-54728af24aca.png)

No, it's not managed by Git.

git version 2.37.0 (Apple Git-136)

**Comment by saltbo** [comment]
> As mentioned above, client-side hooks are local to any given Git repository. This means they are not cloned with the rest of the project and are not version-controlled. As such, maintaining hooks for a team can be tricky.

https://medium.com/@f3igao/get-started-with-git-hooks-5a489725c639

**Comment by theishanbh** [comment]
@saltbo 

What I meant is they are not version controlled and their history cant be maintained but they are used by Git. There are many reasons why Git Hooks are kept client side only.

**Comment by saltbo** [comment]
I want to commit the hooks and managed them by git. But, I found the `core.hooksPath` not managed too...
